require 'PrimesMultiplicationTableGenerator/version'
require 'PrimesMultiplicationTableGenerator/primes_helper.rb'
require 'PrimesMultiplicationTableGenerator/table_generator.rb'

module PrimesMultiplicationTableGenerator
end
